from __future__ import annotations

import re
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from workflow.state.paths import graph_dir, summary_path, workflow_root
from workflow.util.fs import ensure_dir, read_text, write_text
from workflow.util.log import fatal

_INSTALL_HINT = (
    "graphify CLI not found on PATH. Install with "
    "`uv tool install graphifyy` (or `pipx install graphifyy`), "
    "then run `graphify install` once to register the skill."
)


def build_graph(cwd: Path, *, full: bool = False) -> dict:
    """Build or incrementally update the repo graph via the graphify CLI.

    graphify always writes to `<cwd>/graphify-out/`. We move that directory
    into `.workflow/graphify-out/` after each run so all workflow state stays
    under `.workflow/`. Before running we restore the previous output there so
    graphify can perform incremental (cache-based) updates.
    """
    binary = shutil.which("graphify")
    if not binary:
        fatal(_INSTALL_HINT)

    out_dir = workflow_root(cwd) / "graphify-out"
    tmp_dir = cwd / "graphify-out"  # where graphify always writes

    if full:
        cache = out_dir / "cache"
        if cache.exists():
            shutil.rmtree(cache)

    # Restore previous output so graphify can do an incremental update.
    if out_dir.exists() and not tmp_dir.exists():
        shutil.move(str(out_dir), str(tmp_dir))

    proc = subprocess.run(
        [binary, "update", str(cwd)],
        cwd=cwd,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        fatal(
            "graphify failed:\n"
            + (proc.stderr.strip() or proc.stdout.strip() or "(no output)")
        )

    # Move graphify's output from the repo root into .workflow/graphify-out/.
    if tmp_dir.exists():
        if out_dir.exists():
            shutil.rmtree(out_dir)
        shutil.move(str(tmp_dir), str(out_dir))

    report = out_dir / "GRAPH_REPORT.md"
    if not report.exists():
        fatal(f"graphify did not produce {report}")

    ensure_dir(graph_dir(cwd))
    write_text(summary_path(cwd), _projected_summary(cwd, out_dir, report))

    nodes, edges = _parse_counts(proc.stdout + "\n" + proc.stderr)
    return {
        "provider": "graphify",
        "nodes": nodes,
        "edges": edges,
        "report": str(report),
        "graph_json": str(out_dir / "graph.json"),
    }


def _projected_summary(cwd: Path, out_dir: Path, report: Path) -> str:
    ts = datetime.now(timezone.utc).isoformat()
    header = (
        f"<!-- Generated by graphify at {ts}. -->\n"
        f"<!-- Source of truth: {out_dir.relative_to(cwd)}/graph.json -->\n\n"
    )
    return header + read_text(report)


def _parse_counts(text: str) -> tuple[int | None, int | None]:
    m = re.search(r"Rebuilt:\s*(\d+)\s+nodes?,\s*(\d+)\s+edges?", text)
    if not m:
        return None, None
    return int(m.group(1)), int(m.group(2))
